# Generated by Django 3.2.1 on 2021-05-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the author', max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'authors',
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublishingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the publishing company', max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Publishing Company',
                'verbose_name_plural': 'Publishing Companys',
                'db_table': 'publishing_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=255, verbose_name='Title')),
                ('isbn', models.CharField(help_text='International Standard Book Number', max_length=13, verbose_name='ISBN')),
                ('number_of_pages', models.IntegerField(help_text='Number of pages of the book', verbose_name='Number of pages')),
                ('description', models.CharField(help_text='Brief description of the book', max_length=255, verbose_name='Description')),
                ('author', models.ForeignKey(help_text='Authors of the book', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='app.author', verbose_name='Authors')),
                ('publishing_company', models.ForeignKey(help_text='Publishing company of the book', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='app.publishingcompany', verbose_name='Publishing Company')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
    ]
