# Generated by Django 3.2.1 on 2021-05-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Name of the author', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publishingcompany',
            name='name',
            field=models.CharField(help_text='Name of the publishing company', max_length=255, verbose_name='Name'),
        ),
    ]
