# Generated by Django 3.2.1 on 2021-05-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210505_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(default=1, help_text='Edition of the book', max_length=150, verbose_name='Edition'),
            preserve_default=False,
        ),
    ]
